name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  fluttertoast: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png
    - assets/nature.jpg
    - assets/nature2.png
    - assets/insight.png
    - assets/Home-logob.png
    - assets/Home-logobb.png
    - assets/App-logob.png
    - assets/male.png
    - assets/female.png
