// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxlAAVvEkVIhcn9Qum_ruEpaWZEpcrtTk',
    appId: '1:36307055178:web:8b70bdceaf40647c676cb3',
    messagingSenderId: '36307055178',
    projectId: 'mindwave-mobile',
    authDomain: 'mindwave-mobile.firebaseapp.com',
    storageBucket: 'mindwave-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW_rTFpaHt7DowDsoj3z48RHOvKOAz__A',
    appId: '1:36307055178:android:dcb644c0ac6bc91f676cb3',
    messagingSenderId: '36307055178',
    projectId: 'mindwave-mobile',
    storageBucket: 'mindwave-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPhYzNzwnGpp74f88jLYqHINBFUUH0XcE',
    appId: '1:36307055178:ios:eaa9205f96c12673676cb3',
    messagingSenderId: '36307055178',
    projectId: 'mindwave-mobile',
    storageBucket: 'mindwave-mobile.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPhYzNzwnGpp74f88jLYqHINBFUUH0XcE',
    appId: '1:36307055178:ios:eaa9205f96c12673676cb3',
    messagingSenderId: '36307055178',
    projectId: 'mindwave-mobile',
    storageBucket: 'mindwave-mobile.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxlAAVvEkVIhcn9Qum_ruEpaWZEpcrtTk',
    appId: '1:36307055178:web:b29d88bb335ab8f0676cb3',
    messagingSenderId: '36307055178',
    projectId: 'mindwave-mobile',
    authDomain: 'mindwave-mobile.firebaseapp.com',
    storageBucket: 'mindwave-mobile.appspot.com',
  );
}
